name: Run visual regression tests

# Run only after the main test workflow completes successfully
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout tested commit
              uses: actions/checkout@v4
              with:
                  # Ensure we run against the exact commit from the triggering workflow
                  repository: ${{ github.event.workflow_run.head_repository.full_name }}
                  ref: ${{ github.event.workflow_run.head_sha }}

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 10
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Run Vitest tests
              run: pnpm test

            - name: Run visual regression tests
              run: pnpm test:visual
